version: "3.9"
services:
  postgres3:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis3:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # api2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api2
  #   ports:
  #     - "9090:9090"
  #   environment:
  #     - DB_SOURCE=postgresql://root:secret@postgres:5432/pim?sslmode=disable
  #     - REDIS_ADDRESS=redis:6379
  #   depends_on:
  #     - postgres2
  #     - redis2
  #   entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
  #   command: ["/app/main"]
volumes:
  pgdata:
